ae = "/home/flux/models/ae.safetensors"
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_text_encoder_outputs = true
caption_extension = ".txt"
clip_l = "/home/flux/models/clip_l.safetensors"
clip_skip = 1
discrete_flow_shift = 3.0
dynamo_backend = "no"
epoch = 100
fp8_base = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_train_steps = 1200
min_bucket_reso = 256
min_snr_gamma = 7
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 128
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_dim = 128
network_module = "networks.lora_flux"
network_train_unet_only = true
noise_offset = 0.05
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "Adafactor"
output_dir = "/home/flux/datasets/[ID]/output"
output_name = "[ID]"
pretrained_model_name_or_path = "/home/flux/models/flux1-dev.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_sampler = "euler"
save_model_as = "safetensors"
save_precision = "float"
sdpa = true
t5xxl = "/home/flux/models/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = []
timestep_sampling = "sigmoid"
train_batch_size = 1
train_data_dir = "/home/flux/datasets/[ID]/input"
unet_lr = 6e-5
wandb_run_name = "[ID]"
